typography_spectrum: 0.1735456446185708
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.1903599053621292
  saturation: 0.028121870243921876
  rhythmicContrast: 0.019278069026768208
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75286
analytics:
  google: null
  facebook: null
  twitter: null
name: PK
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: PK Rasam
description: emerging Business Technology Czar
purpose: []
