name: PK
favicon: null
layout_spectrum: 0.7126421842258424
typography_spectrum: 0.1735456446185708
title: PK Rasam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4259312213398516
  lightness: 0.1903599053621292
  saturation: 0.028121870243921876
  rhythmicContrast: 0.019278069026768208
purpose: []
